"""
Sentinel-1 annotation XML parsing — real per-pixel acquisition timing.

This is the missing link between "a pixel at (row, col) in an extracted
SLC GeoTIFF" and "the exact acquisition time and slant range needed to
feed geolocation.py's orbit-based solver" — that information does not
exist in the GeoTIFF itself (a general raster format); it lives in a
separate XML file inside the .SAFE archive.

Field paths confirmed against ESA's own Mission Performance Centre
documentation (Thermal Denoising of Products Generated by the S-1 IPF,
MPC-0392):

    /product/imageAnnotation/imageInformation/productFirstLineUtcTime
    /product/imageAnnotation/imageInformation/azimuthTimeInterval
    /product/imageAnnotation/imageInformation/slantRangeTime
    /product/generalAnnotation/productInformation/rangeSamplingRate
"""

from __future__ import annotations

import logging
import zipfile
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Union

logger = logging.getLogger("pygeofetch.insar.annotation")

SPEED_OF_LIGHT = 299792458.0


@dataclass
class SLCGeometry:
    """
    Real per-pixel acquisition geometry for one Sentinel-1 SLC measurement,
    parsed from its annotation XML — everything needed to convert a pixel
    (row, col) into an exact acquisition time and slant range.
    """

    first_line_time: datetime
    azimuth_time_interval_s: float
    near_range_time_s: float
    range_sampling_rate_hz: float
    n_lines: int
    n_columns: int

    def azimuth_time(self, row: float) -> datetime:
        """Exact acquisition time of a given (possibly fractional) row."""
        return self.first_line_time + timedelta(
            seconds=row * self.azimuth_time_interval_s
        )

    def range_time(self, col: float) -> float:
        """Two-way slant range time (seconds) of a given (possibly
        fractional) column."""
        return self.near_range_time_s + col / self.range_sampling_rate_hz

    def slant_range_m(self, col: float) -> float:
        """One-way slant range (metres) of a given column."""
        return self.range_time(col) * SPEED_OF_LIGHT / 2.0

    def row_for_azimuth_time(self, t: datetime) -> float:
        """Inverse of azimuth_time(): which (fractional) row corresponds
        to a given acquisition time."""
        return (t - self.first_line_time).total_seconds() / self.azimuth_time_interval_s

    def col_for_range_time(self, range_time_s: float) -> float:
        """Inverse of range_time(): which (fractional) column corresponds
        to a given two-way range time."""
        return (range_time_s - self.near_range_time_s) * self.range_sampling_rate_hz


def parse_slc_geometry(
    safe_zip_path: Union[str, Path], member_hint: Optional[str] = None
) -> SLCGeometry:
    """
    Parse real per-pixel acquisition geometry from a Sentinel-1 SAFE
    archive's annotation XML.

    Args:
        safe_zip_path: Path to the downloaded .SAFE.zip archive.
        member_hint:   Optional substring to disambiguate which
                       annotation file to use when multiple sub-swaths/
                       polarisations are present (e.g. "iw2-vv" or the
                       measurement filename this geometry corresponds
                       to). If None, uses the first annotation XML found.

    Returns:
        A real SLCGeometry with the exact timing needed to feed
        geolocation.py's solve_ground_point().

    Raises:
        ValueError if no annotation XML is found, or a required field
        is missing — surfaced clearly rather than returning a
        geometry built from guessed/default values.
    """
    import xml.etree.ElementTree as ET

    with zipfile.ZipFile(safe_zip_path) as zf:
        candidates = [
            n for n in zf.namelist()
            if "/annotation/" in n and n.lower().endswith(".xml")
            and "/calibration/" not in n.lower()
        ]
        if member_hint:
            filtered = [n for n in candidates if member_hint.lower() in n.lower()]
            if filtered:
                candidates = filtered

        if not candidates:
            raise ValueError(
                f"{safe_zip_path}: no annotation XML found — this doesn't "
                f"look like a real Sentinel-1 SAFE archive, or the "
                f"expected internal structure has changed."
            )

        with zf.open(candidates[0]) as f:
            root = ET.parse(f).getroot()

    def get_text(path: str) -> str:
        elem = root.find(path)
        if elem is None or elem.text is None:
            raise ValueError(
                f"{safe_zip_path}: required annotation field missing: {path}"
            )
        return elem.text

    first_line_str = get_text(".//imageAnnotation/imageInformation/productFirstLineUtcTime")
    first_line_time = datetime.fromisoformat(first_line_str)

    geometry = SLCGeometry(
        first_line_time=first_line_time,
        azimuth_time_interval_s=float(
            get_text(".//imageAnnotation/imageInformation/azimuthTimeInterval")
        ),
        near_range_time_s=float(
            get_text(".//imageAnnotation/imageInformation/slantRangeTime")
        ),
        range_sampling_rate_hz=float(
            get_text(".//generalAnnotation/productInformation/rangeSamplingRate")
        ),
        n_lines=int(get_text(".//imageAnnotation/imageInformation/numberOfLines")),
        n_columns=int(get_text(".//imageAnnotation/imageInformation/numberOfColumns")),
    )

    logger.info(
        "Parsed real SLC geometry from %s: %d x %d, starting %s",
        Path(safe_zip_path).name, geometry.n_lines, geometry.n_columns,
        geometry.first_line_time,
    )
    return geometry
