"""
Sentinel-1 annotation XML parsing — real per-pixel acquisition timing.

This is the missing link between "a pixel at (row, col) in an extracted
SLC GeoTIFF" and "the exact acquisition time and slant range needed to
feed geolocation.py's orbit-based solver" — that information does not
exist in the GeoTIFF itself (a general raster format); it lives in a
separate XML file inside the .SAFE archive.

Field paths confirmed against ESA's own Mission Performance Centre
documentation (Thermal Denoising of Products Generated by the S-1 IPF,
MPC-0392):

    /product/imageAnnotation/imageInformation/productFirstLineUtcTime
    /product/imageAnnotation/imageInformation/azimuthTimeInterval
    /product/imageAnnotation/imageInformation/slantRangeTime
    /product/generalAnnotation/productInformation/rangeSamplingRate

Dimension field paths confirmed separately, against ESA's Sentinel-1
Product Specification (MPC-0240), which documents renaming
numberOfAzimuthLines -> numberOfLines and numberOfRangeSamples ->
numberOfSamples:

    /product/imageAnnotation/imageInformation/numberOfLines
    /product/imageAnnotation/imageInformation/numberOfSamples

("numberOfColumns" is not a real field in this schema at all -- an
earlier, unverified assumption here that only surfaced against real
Sentinel-1 data, since synthetic tests built on the same assumption
couldn't have caught their own premise being wrong.)
"""

from __future__ import annotations

import logging
import zipfile
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, List, Optional, Union

logger = logging.getLogger("pygeofetch.insar.annotation")

SPEED_OF_LIGHT = 299792458.0


@dataclass
class SLCGeometry:
    """
    Real per-pixel acquisition geometry for one Sentinel-1 SLC measurement,
    parsed from its annotation XML — everything needed to convert a pixel
    (row, col) into an exact acquisition time and slant range.
    """

    first_line_time: datetime
    azimuth_time_interval_s: float
    near_range_time_s: float
    range_sampling_rate_hz: float
    n_lines: int
    n_columns: int

    def azimuth_time(self, row: float) -> datetime:
        """Exact acquisition time of a given (possibly fractional) row."""
        return self.first_line_time + timedelta(
            seconds=row * self.azimuth_time_interval_s
        )

    def range_time(self, col: float) -> float:
        """Two-way slant range time (seconds) of a given (possibly
        fractional) column."""
        return self.near_range_time_s + col / self.range_sampling_rate_hz

    def slant_range_m(self, col: float) -> float:
        """One-way slant range (metres) of a given column."""
        return self.range_time(col) * SPEED_OF_LIGHT / 2.0

    def row_for_azimuth_time(self, t: datetime) -> float:
        """Inverse of azimuth_time(): which (fractional) row corresponds
        to a given acquisition time."""
        return (t - self.first_line_time).total_seconds() / self.azimuth_time_interval_s

    def col_for_range_time(self, range_time_s: float) -> float:
        """Inverse of range_time(): which (fractional) column corresponds
        to a given two-way range time."""
        return (range_time_s - self.near_range_time_s) * self.range_sampling_rate_hz


def parse_slc_geometry(
    safe_zip_path: Union[str, Path], member_hint: Optional[str] = None
) -> SLCGeometry:
    """
    Parse real per-pixel acquisition geometry from a Sentinel-1 SAFE
    archive's annotation XML.

    Args:
        safe_zip_path: Path to the downloaded .SAFE.zip archive.
        member_hint:   Optional substring to disambiguate which
                       annotation file to use when multiple sub-swaths/
                       polarisations are present (e.g. "iw2-vv" or the
                       measurement filename this geometry corresponds
                       to). If None, uses the first annotation XML found.

    Returns:
        A real SLCGeometry with the exact timing needed to feed
        geolocation.py's solve_ground_point().

    Raises:
        ValueError if no annotation XML is found, or a required field
        is missing — surfaced clearly rather than returning a
        geometry built from guessed/default values.
    """
    import xml.etree.ElementTree as ET

    with zipfile.ZipFile(safe_zip_path) as zf:
        candidates = [
            n for n in zf.namelist()
            if "/annotation/" in n and n.lower().endswith(".xml")
            and "/calibration/" not in n.lower()
            # Exclude RFI (radio frequency interference) report files --
            # confirmed real, present in Sentinel-1 products since IPF
            # 3.40, living in this same annotation tree. Their filenames
            # are prefixed "rfi-" (not the satellite-platform prefix
            # "s1a-"/"s1b-" real per-swath annotation files use), and
            # critically can ALSO contain "-slc-" for SLC products
            # (confirmed by testing: an earlier "-slc-" based filter was
            # insufficient for exactly this reason), so the prefix is
            # the only reliable differentiator, not substring content.
            and not Path(n).name.lower().startswith("rfi-")
            and "/rfi/" not in n.lower()
        ]
        if member_hint:
            filtered = [n for n in candidates if member_hint.lower() in n.lower()]
            if filtered:
                candidates = filtered

        if not candidates:
            raise ValueError(
                f"{safe_zip_path}: no annotation XML found — this doesn't "
                f"look like a real Sentinel-1 SAFE archive, or the "
                f"expected internal structure has changed."
            )

        with zf.open(candidates[0]) as f:
            root = ET.parse(f).getroot()

    def get_text(path: str) -> str:
        elem = root.find(path)
        if elem is None or elem.text is None:
            raise ValueError(
                f"{safe_zip_path}: required annotation field missing: {path}"
            )
        return elem.text

    first_line_str = get_text(".//imageAnnotation/imageInformation/productFirstLineUtcTime")
    first_line_time = datetime.fromisoformat(first_line_str)

    geometry = SLCGeometry(
        first_line_time=first_line_time,
        azimuth_time_interval_s=float(
            get_text(".//imageAnnotation/imageInformation/azimuthTimeInterval")
        ),
        near_range_time_s=float(
            get_text(".//imageAnnotation/imageInformation/slantRangeTime")
        ),
        range_sampling_rate_hz=float(
            get_text(".//generalAnnotation/productInformation/rangeSamplingRate")
        ),
        n_lines=int(get_text(".//imageAnnotation/imageInformation/numberOfLines")),
        # Real field name confirmed against ESA's own Product
        # Specification (MPC-0240): "Renamed numberOfRangeSamples to
        # numberOfSamples". "numberOfColumns" was never a real field in
        # this schema at all -- an incorrect assumption in earlier
        # research here, caught only against real Sentinel-1 data,
        # since the synthetic tests built on that same assumption
        # couldn't have caught their own premise being wrong.
        n_columns=int(get_text(".//imageAnnotation/imageInformation/numberOfSamples")),
    )

    logger.info(
        "Parsed real SLC geometry from %s: %d x %d, starting %s",
        Path(safe_zip_path).name, geometry.n_lines, geometry.n_columns,
        geometry.first_line_time,
    )
    return geometry


def parse_chirp_bandwidth(safe_zip_path: Union[str, Path], member_hint: Optional[str] = None) -> float:
    """
    Real, per-product chirp bandwidth (Hz), read directly from a real
    Sentinel-1 SAFE archive's own annotation XML -- not approximated
    from general documentation, which showed real ambiguity across
    sources (56.5 MHz commonly cited, but ESA's own system overview
    table lists different values, likely varying per IW sub-swath,
    without a clear, confident way to map table columns to swaths).

    Real, confirmed XML field names and formula: verified directly
    against ISCE (JPL/Caltech's own, established, widely-used
    open-source InSAR processing software)'s real Sentinel1.py parser,
    which reads exactly these two fields and computes bandwidth as
    their product -- standard, real chirp radar physics (bandwidth =
    ramp rate * pulse duration), not an assumption made here.

    Raises:
        ValueError if the annotation XML or required fields are
        missing -- surfaced clearly rather than falling back to an
        approximate, possibly-wrong default value.
    """
    import xml.etree.ElementTree as ET

    with zipfile.ZipFile(safe_zip_path) as zf:
        candidates = [
            n for n in zf.namelist()
            if "/annotation/" in n and n.lower().endswith(".xml")
            and "/calibration/" not in n.lower()
            and not Path(n).name.lower().startswith("rfi-")
            and "/rfi/" not in n.lower()
        ]
        if member_hint:
            filtered = [n for n in candidates if member_hint.lower() in n.lower()]
            if filtered:
                candidates = filtered
        if not candidates:
            raise ValueError(
                f"{safe_zip_path}: no annotation XML found — cannot "
                f"read real chirp bandwidth."
            )
        with zf.open(candidates[0]) as f:
            root = ET.parse(f).getroot()

    def get_text(path: str) -> str:
        elem = root.find(path)
        if elem is None or elem.text is None:
            raise ValueError(
                f"{safe_zip_path}: required chirp field missing: {path} "
                f"(real field path confirmed against ISCE's own parser — "
                f"if this is missing, the product's annotation schema may "
                f"differ from what was verified)."
            )
        return elem.text

    pulse_length_s = float(get_text(
        ".//generalAnnotation/downlinkInformationList/downlinkInformation/"
        "downlinkValues/txPulseLength"
    ))
    ramp_rate_hz_per_s = float(get_text(
        ".//generalAnnotation/downlinkInformationList/downlinkInformation/"
        "downlinkValues/txPulseRampRate"
    ))
    bandwidth_hz = abs(ramp_rate_hz_per_s * pulse_length_s)

    logger.info(
        "Parsed real chirp bandwidth from %s: %.2f MHz (pulse length=%.2f us, ramp rate=%.4f MHz/us)",
        Path(safe_zip_path).name, bandwidth_hz / 1e6,
        pulse_length_s * 1e6, ramp_rate_hz_per_s / 1e12,
    )
    return bandwidth_hz


@dataclass
class BurstInfo:
    """
    Real per-burst timing and valid-sample metadata for one Sentinel-1
    TOPS burst, parsed from the same annotation XML's swathTiming
    element.

    Real, confirmed field structure (verified against multiple
    independent sources, not assumed): a real, working extraction
    script actually used against the Copernicus Data Space Ecosystem
    (github.com/eu-cdse/utilities, sentinel1_burst_extractor.sh), a
    real academic SAR analysis tool's own parsed representation
    (xsarslc), and SNAP's own Java source for its S-1 TOPS Deburst
    operator (SliceAssemblyOp.java) -- all three independently confirm
    the same real structure this dataclass captures.

    first_valid_sample/last_valid_sample are real, per-LINE arrays
    (not a single rectangle for the whole burst) -- the valid data
    region within a TOPS burst is not rectangular; it varies row by
    row because of the burst's Doppler-dependent acquisition geometry.
    This is the exact information deburst needs to correctly trim each
    burst to its real, unique (non-overlapping) contribution before
    stitching bursts into one continuous image.
    """

    burst_index: int
    azimuth_time: datetime
    sensing_time: Optional[datetime]
    byte_offset: int
    first_valid_sample: Any  # int array, one entry per line in this burst; -1 = no valid data on that line
    last_valid_sample: Any


@dataclass
class SwathTiming:
    """
    Real burst structure for one Sentinel-1 TOPS sub-swath: uniform
    per-burst dimensions plus the real, individual timing/valid-sample
    metadata for every burst -- everything needed to correctly deburst
    (Step 2) and to compute real per-burst-overlap ESD (Step 3),
    instead of the current whole-image approximation.
    """

    lines_per_burst: int
    samples_per_burst: int
    bursts: List[BurstInfo]  # real burst count = len(bursts)


def parse_burst_info(
    safe_zip_path: Union[str, Path], member_hint: Optional[str] = None
) -> SwathTiming:
    """
    Parse real per-burst timing and valid-sample metadata from a
    Sentinel-1 SAFE archive's annotation XML.

    Real field paths (confirmed against the same independent sources
    cited in BurstInfo's docstring):

        /product/swathTiming/linesPerBurst
        /product/swathTiming/samplesPerBurst
        /product/swathTiming/burstList  (has a real "count" attribute)
        /product/swathTiming/burstList/burst/azimuthTime
        /product/swathTiming/burstList/burst/sensingTime
        /product/swathTiming/burstList/burst/byteOffset
        /product/swathTiming/burstList/burst/firstValidSample
        /product/swathTiming/burstList/burst/lastValidSample

    firstValidSample/lastValidSample are real, space-separated text
    content (one integer per line in the burst, confirmed real format
    -- not a nested per-line XML structure), parsed here into real
    integer arrays.

    Args:
        safe_zip_path: Path to the downloaded .SAFE.zip archive.
        member_hint:   Same disambiguation convention as
                       parse_slc_geometry() -- must resolve to the
                       SAME annotation file for a given call, since
                       burst structure is real, per-sub-swath data.

    Returns:
        Real SwathTiming with every burst's real timing and per-line
        valid-sample boundaries.

    Raises:
        ValueError if no annotation XML is found, or required fields
        are missing -- surfaced clearly, not silently defaulted.
    """
    import numpy as np
    import xml.etree.ElementTree as ET

    with zipfile.ZipFile(safe_zip_path) as zf:
        candidates = [
            n for n in zf.namelist()
            if "/annotation/" in n and n.lower().endswith(".xml")
            and "/calibration/" not in n.lower()
            and not Path(n).name.lower().startswith("rfi-")
            and "/rfi/" not in n.lower()
        ]
        if member_hint:
            filtered = [n for n in candidates if member_hint.lower() in n.lower()]
            if filtered:
                candidates = filtered

        if not candidates:
            raise ValueError(
                f"{safe_zip_path}: no annotation XML found — this doesn't "
                f"look like a real Sentinel-1 SAFE archive, or the "
                f"expected internal structure has changed."
            )

        with zf.open(candidates[0]) as f:
            root = ET.parse(f).getroot()

    def get_text(path: str) -> str:
        elem = root.find(path)
        if elem is None or elem.text is None:
            raise ValueError(
                f"{safe_zip_path}: required swathTiming field missing: {path}"
            )
        return elem.text

    lines_per_burst = int(get_text(".//swathTiming/linesPerBurst"))
    samples_per_burst = int(get_text(".//swathTiming/samplesPerBurst"))

    burst_list_elem = root.find(".//swathTiming/burstList")
    if burst_list_elem is None:
        raise ValueError(f"{safe_zip_path}: no burstList found in swathTiming")

    burst_elems = burst_list_elem.findall("burst")
    declared_count = burst_list_elem.get("count")
    if declared_count is not None and int(declared_count) != len(burst_elems):
        logger.warning(
            "%s: burstList count attribute (%s) does not match the real "
            "number of <burst> elements found (%d) — using the real "
            "count of parsed elements, not the declared attribute.",
            Path(safe_zip_path).name, declared_count, len(burst_elems),
        )

    bursts = []
    for i, burst_elem in enumerate(burst_elems):
        azimuth_time_elem = burst_elem.find("azimuthTime")
        if azimuth_time_elem is None or azimuth_time_elem.text is None:
            raise ValueError(
                f"{safe_zip_path}: burst {i} missing required azimuthTime"
            )
        azimuth_time = datetime.fromisoformat(azimuth_time_elem.text)

        sensing_time_elem = burst_elem.find("sensingTime")
        sensing_time = (
            datetime.fromisoformat(sensing_time_elem.text)
            if sensing_time_elem is not None and sensing_time_elem.text
            else None
        )

        byte_offset_elem = burst_elem.find("byteOffset")
        byte_offset = (
            int(byte_offset_elem.text)
            if byte_offset_elem is not None and byte_offset_elem.text
            else -1
        )

        first_valid_elem = burst_elem.find("firstValidSample")
        last_valid_elem = burst_elem.find("lastValidSample")
        if first_valid_elem is None or last_valid_elem is None:
            raise ValueError(
                f"{safe_zip_path}: burst {i} missing firstValidSample/"
                f"lastValidSample — cannot determine real valid-data "
                f"boundaries for this burst."
            )
        first_valid_sample = np.array(
            [int(v) for v in first_valid_elem.text.split()], dtype=np.int32
        )
        last_valid_sample = np.array(
            [int(v) for v in last_valid_elem.text.split()], dtype=np.int32
        )
        if len(first_valid_sample) != lines_per_burst:
            raise ValueError(
                f"{safe_zip_path}: burst {i} firstValidSample has "
                f"{len(first_valid_sample)} entries, expected "
                f"linesPerBurst={lines_per_burst} — real annotation "
                f"structure does not match what this parser expects."
            )

        bursts.append(BurstInfo(
            burst_index=i,
            azimuth_time=azimuth_time,
            sensing_time=sensing_time,
            byte_offset=byte_offset,
            first_valid_sample=first_valid_sample,
            last_valid_sample=last_valid_sample,
        ))

    logger.info(
        "Parsed real burst metadata from %s: %d bursts, %d lines/burst, "
        "%d samples/burst",
        Path(safe_zip_path).name, len(bursts), lines_per_burst, samples_per_burst,
    )

    return SwathTiming(
        lines_per_burst=lines_per_burst,
        samples_per_burst=samples_per_burst,
        bursts=bursts,
    )